### ISSUE TITLE
The app can't work after development sign.

### ISSUE THREAD

**Issue by ghost** [sethlu/electron-distribution-guide#2]
Hi, I just signed my app according to your doc https://github.com/sethlu/electron-distribution-guide/blob/master/DevelopmentSignedApplication.md . But my app can't work any more,just froze in a white screen.The devtools also can't work.Do you know why?
I'm using electron v1.3.1.

Thanks

**Comment by sethlu** [comment]
Hi @ycinfinity, thanks for reporting this issue. Would you mind first going to your Console and checking if there be any error logs thrown at app launching? Let me know and I could further assist with the problem.

---

I would say that this current signing flow is still conceptual; for a more convenient solution, you may would like to try `electron-osx-sign` which does not yet involve provisioning profiles.

**Comment by ghost** [comment]
Thanks for your answer.I can't get any message from the console.But the "electron-osx-sign" works.

**Comment by sethlu** [comment]
@ycinfinity glad the alternative worked! 😸 Closing this issue for now.
