### ISSUE TITLE
The build app do not show up on ITC

### ISSUE THREAD

**Issue by wuwenxian** [sethlu/electron-distribution-guide#3]
I followed your Mac App Store Deployment strict to sign my mac app. After code signed , the app is verified valid on disk. Then I uploaded the pkg file to ITC using Application Loader(ver 3.5), I can saw that the build is processing during uploading. But It disapppear after uploaded successed, and it do not show up anymore.

Can anyone help me? Please. The electron version of my choosing is 1.3.5.

**Comment by wuwenxian** [comment]
Mybe the issue is that I take the darwin electron version not the mas version. I'll check it.

**Comment by wuwenxian** [comment]
I used the mas platform electron ver 1.2.6, the issue exist yet.

**Comment by sethlu** [comment]
Hi @wuwenxian would you start by checking if all your contracts on iTunes Connects have been signed? Now as no error is thrown after binary uploaded, I find it slightly hard to conclude the issue lies during codesign.

**Comment by wuwenxian** [comment]
Thank you very much.
I find the reason finally. I have copyed some python scripts to the App/Contents/MacOS folder before codesign. Even I have signed this python scripts. And codesign verify is valid, but the ITC building is faild.

**Comment by wuwenxian** [comment]
Thank you very much.
I find the reason finally. I have copyed some python scripts to the App/Contents/MacOS folder before codesign. Even I have signed this python scripts. And codesign verify is valid, but the ITC building is faild.
